"""query fix

Revision ID: 04bc3e60f51d
Revises: 932e1bc74ef4
Create Date: 2023-08-21 12:21:59.624402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bc3e60f51d'
down_revision = '932e1bc74ef4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'systemId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat', 'isAnonymous',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('query', sa.Column('is_valid', sa.Boolean(), nullable=True))
    op.drop_constraint('query_query_type_id_fkey', 'query', type_='foreignkey')
    op.drop_column('query', 'query_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('query_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('query_query_type_id_fkey', 'query', 'query_type', ['query_type_id'], ['id'])
    op.drop_column('query', 'is_valid')
    op.alter_column('chat', 'isAnonymous',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('chat', 'systemId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
