"""add tables

Revision ID: 09901d9e67e3
Revises: daa817e5adf2
Create Date: 2023-07-11 09:49:58.085978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09901d9e67e3'
down_revision = 'daa817e5adf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('systemTypeId', sa.Integer(), nullable=True),
    sa.Column('bugTracker', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('systemId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('isAnonymous', sa.Boolean(), nullable=True),
    sa.Column('sessionId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    op.drop_table('system')
    # ### end Alembic commands ###
