"""fix query table

Revision ID: 17c8d853a123
Revises: de18042268db
Create Date: 2023-07-13 12:14:41.519446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c8d853a123'
down_revision = 'de18042268db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('query_table')
    op.create_foreign_key(None, 'query', 'query_type', ['queryTypeId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'query', type_='foreignkey')
    op.create_table('query_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='query_table_pkey')
    )
    op.drop_table('query_type')
    # ### end Alembic commands ###
