"""rework is_useful in query

Revision ID: 17db9b2007b7
Revises: bbb106919904
Create Date: 2023-08-29 11:00:59.256334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17db9b2007b7'
down_revision = 'bbb106919904'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
