"""rework useful in query

Revision ID: 18e66dfd59ae
Revises: 17db9b2007b7
Create Date: 2023-08-29 11:45:52.107476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18e66dfd59ae'
down_revision = '17db9b2007b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('useful', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    op.drop_column('query', 'is_useful')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('is_useful', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('query', 'useful')
    # ### end Alembic commands ###
