"""rework useful in query

Revision ID: 1adacc418f42
Revises: 18e66dfd59ae
Create Date: 2023-08-29 12:53:36.298091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1adacc418f42'
down_revision = '18e66dfd59ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('useful_faq', sa.Boolean(), nullable=True))
    op.add_column('query', sa.Column('useful_article', sa.Boolean(), nullable=True))
    op.add_column('query', sa.Column('useful_law', sa.Boolean(), nullable=True))
    op.drop_column('query', 'useful')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('useful', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('query', 'useful_law')
    op.drop_column('query', 'useful_article')
    op.drop_column('query', 'useful_faq')
    # ### end Alembic commands ###
