"""fix tables

Revision ID: 1c8a3b9a23e5
Revises: 60d935bf47a5
Create Date: 2023-07-13 11:49:50.785698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8a3b9a23e5'
down_revision = '60d935bf47a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('system', sa.Column('system_type_id', sa.Integer(), nullable=True))
    op.drop_constraint('system_systemTypeId_fkey', 'system', type_='foreignkey')
    op.create_foreign_key(None, 'system', 'system type', ['system_type_id'], ['id'])
    op.drop_column('system', 'systemTypeId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system', sa.Column('systemTypeId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'system', type_='foreignkey')
    op.create_foreign_key('system_systemTypeId_fkey', 'system', 'systemType', ['systemTypeId'], ['id'])
    op.drop_column('system', 'system_type_id')
    op.drop_table('system type')
    # ### end Alembic commands ###
