"""fix tables

Revision ID: 1d16b49d3183
Revises: b135ed14f252
Create Date: 2023-07-13 11:58:49.812066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d16b49d3183'
down_revision = 'b135ed14f252'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('systemType')
    op.drop_constraint('system_system_type_id_fkey', 'system', type_='foreignkey')
    op.create_foreign_key(None, 'system', 'system_type', ['system_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system', type_='foreignkey')
    op.create_foreign_key('system_system_type_id_fkey', 'system', 'system type', ['system_type_id'], ['id'])
    op.create_table('systemType',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"systemType_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='systemType_pkey')
    )
    op.drop_table('system_type')
    # ### end Alembic commands ###
