"""add fixed_fill in query table

Revision ID: 1f9dae971681
Revises: e4ce65b48936
Create Date: 2023-09-03 23:01:15.163364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9dae971681'
down_revision = 'e4ce65b48936'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
