"""add tables

Revision ID: 60d935bf47a5
Revises: bb9f2b11a1e1
Create Date: 2023-07-13 10:53:52.771823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d935bf47a5'
down_revision = 'bb9f2b11a1e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queryTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('queryTypeId', sa.Integer(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chatId'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['queryTypeId'], ['queryTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query')
    op.drop_table('queryTable')
    # ### end Alembic commands ###
