"""fix query table

Revision ID: 71042f12968f
Revises: fce72bca9a2f
Create Date: 2023-07-13 12:09:15.386685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71042f12968f'
down_revision = 'fce72bca9a2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('query_queryTypeId_fkey', 'query', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('query_queryTypeId_fkey', 'query', 'queryTable', ['queryTypeId'], ['id'])
    # ### end Alembic commands ###
