"""add comment in query table

Revision ID: 77ba856e1442
Revises: 1adacc418f42
Create Date: 2023-08-31 10:16:00.512384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ba856e1442'
down_revision = '1adacc418f42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query', 'comment')
    # ### end Alembic commands ###
