"""fix query table

Revision ID: 790b40a502c8
Revises: 71042f12968f
Create Date: 2023-07-13 12:09:42.519430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790b40a502c8'
down_revision = '71042f12968f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('queryTable')
    op.create_foreign_key(None, 'query', 'query_table', ['queryTypeId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'query', type_='foreignkey')
    op.create_table('queryTable',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"queryTable_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='queryTable_pkey')
    )
    op.drop_table('query_table')
    # ### end Alembic commands ###
