"""fix table

Revision ID: 932e1bc74ef4
Revises: f2600a247bde
Create Date: 2023-07-18 10:37:30.538178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932e1bc74ef4'
down_revision = 'f2600a247bde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chat', 'system', ['systemId'], ['id'])
    op.add_column('query', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.add_column('query', sa.Column('query_type_id', sa.Integer(), nullable=True))
    op.drop_constraint('query_queryTypeId_fkey', 'query', type_='foreignkey')
    op.drop_constraint('query_chatId_fkey', 'query', type_='foreignkey')
    op.create_foreign_key(None, 'query', 'query_type', ['query_type_id'], ['id'])
    op.create_foreign_key(None, 'query', 'chat', ['chat_id'], ['id'])
    op.drop_column('query', 'chatId')
    op.drop_column('query', 'queryTypeId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('queryTypeId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('query', sa.Column('chatId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'query', type_='foreignkey')
    op.drop_constraint(None, 'query', type_='foreignkey')
    op.create_foreign_key('query_chatId_fkey', 'query', 'chat', ['chatId'], ['id'])
    op.create_foreign_key('query_queryTypeId_fkey', 'query', 'query_type', ['queryTypeId'], ['id'])
    op.drop_column('query', 'query_type_id')
    op.drop_column('query', 'chat_id')
    op.drop_constraint(None, 'chat', type_='foreignkey')
    # ### end Alembic commands ###
