"""fix tables

Revision ID: b135ed14f252
Revises: 1c8a3b9a23e5
Create Date: 2023-07-13 11:58:04.484925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b135ed14f252'
down_revision = '1c8a3b9a23e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
