"""add systemType table

Revision ID: bb9f2b11a1e1
Revises: 09901d9e67e3
Create Date: 2023-07-11 10:31:46.253497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9f2b11a1e1'
down_revision = '09901d9e67e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systemType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'system', 'systemType', ['systemTypeId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system', type_='foreignkey')
    op.drop_table('systemType')
    # ### end Alembic commands ###
