"""add is_useful in query

Revision ID: bbb106919904
Revises: 8238b576c01a
Create Date: 2023-08-28 14:20:44.833292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb106919904'
down_revision = '8238b576c01a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('is_useful', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query', 'is_useful')
    # ### end Alembic commands ###
