"""fix query table

Revision ID: de18042268db
Revises: 790b40a502c8
Create Date: 2023-07-13 12:13:58.541210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de18042268db'
down_revision = '790b40a502c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('query_queryTypeId_fkey', 'query', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('query_queryTypeId_fkey', 'query', 'query_table', ['queryTypeId'], ['id'])
    # ### end Alembic commands ###
