"""add fixed in query table

Revision ID: e4ce65b48936
Revises: 77ba856e1442
Create Date: 2023-09-03 21:54:42.824038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ce65b48936'
down_revision = '77ba856e1442'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('fixed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query', 'fixed')
    # ### end Alembic commands ###
