"""fix table

Revision ID: f2600a247bde
Revises: d1c12f2993b0
Create Date: 2023-07-13 15:30:14.849177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2600a247bde'
down_revision = 'd1c12f2993b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system', sa.Column('bug_tracker', sa.String(), nullable=True))
    op.drop_column('system', 'bugTracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system', sa.Column('bugTracker', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('system', 'bug_tracker')
    # ### end Alembic commands ###
