"""delete table

Revision ID: fce72bca9a2f
Revises: 1d16b49d3183
Create Date: 2023-07-13 11:59:17.994019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce72bca9a2f'
down_revision = '1d16b49d3183'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system type',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"system type_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system type_pkey')
    )
    # ### end Alembic commands ###
